export const ADD_TODO_LIST_REQUEST = '@task/ADD_TODO_LIST_REQUEST'
export const TODO_FETCH_FAILED = '@task/TODO_FETCH_FAILED'
export const ADD_TASK = '@task/ADD_TASK'
export const REMOVE_TASK_BY_ID = '@task/REMOVE_TASK_BY_ID'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
